<!DOCTYPE html>
<html>
<body>

<?php
	echo "<h1>Escolha um dos scripts abaixo:<br/></h1>";
	echo '<a href="EXERCICIOS/EX01.PHP"><h2>Exercício 01</h2></a>';
	echo '<a href="EXERCICIOS/EX02.PHP"><h2>Exercício 02</h2></a>';
	echo '<a href="EXERCICIOS/EX03.PHP"><h2>Exercício 03</h2></a>';
	echo '<a href="EXERCICIOS/EX04.PHP"><h2>Exercício 04</h2></a>';
	echo '<a href="EXERCICIOS/EX05.PHP"><h2>Exercício 05</h2></a>';
	echo '<a href="EXERCICIOS/EX06.PHP"><h2>Exercício 06</h2></a>';
	echo '<a href="EXERCICIOS/EX07.PHP"><h2>Exercício 07</h2></a>';
	echo '<a href="EXERCICIOS/EX08.PHP"><h2>Exercício 08</h2></a>';
	echo '<a href="EXERCICIOS/EX09.PHP"><h2>Exercício 09</h2></a>';
	echo '<a href="EXERCICIOS/EX10.PHP"><h2>Exercício 10</h2></a>';
	echo '<a href="EXERCICIOS/EX11.PHP"><h2>Exercício 11</h2></a>';
	echo '<a href="EXERCICIOS/EX12.PHP"><h2>Exercício 12</h2></a>';
	//echo "<h2>C:\\xampp\\htdocs\\PHP</h2>";
?>
</body>
</html>